import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUserOnboardingTable1782726352580 implements MigrationInterface {
    name = 'AddUserOnboardingTable1782726352580'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_webhooks" ("id" varchar PRIMARY KEY NOT NULL, "sessionId" varchar NOT NULL, "url" varchar(2048) NOT NULL, "events" text NOT NULL DEFAULT ('["message.received"]'), "secret" varchar(255), "headers" text NOT NULL DEFAULT ('{}'), "active" boolean NOT NULL DEFAULT (1), "retryCount" integer NOT NULL DEFAULT (3), "lastTriggeredAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_d209715bb62b12255e825580af6" FOREIGN KEY ("sessionId") REFERENCES "sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_webhooks"("id", "sessionId", "url", "events", "secret", "headers", "active", "retryCount", "lastTriggeredAt", "createdAt", "updatedAt") SELECT "id", "sessionId", "url", "events", "secret", "headers", "active", "retryCount", "lastTriggeredAt", "createdAt", "updatedAt" FROM "webhooks"`);
        await queryRunner.query(`DROP TABLE "webhooks"`);
        await queryRunner.query(`ALTER TABLE "temporary_webhooks" RENAME TO "webhooks"`);
        await queryRunner.query(`CREATE TABLE "user_onboarding" ("id" varchar PRIMARY KEY NOT NULL, "chatId" varchar(50) NOT NULL, "state" varchar(30) NOT NULL DEFAULT ('IDLE'), "data" text NOT NULL DEFAULT ('{}'))`);
        await queryRunner.query(`CREATE INDEX "IDX_f0680ed02caf690b052be1d6cb" ON "user_onboarding" ("chatId") `);
        await queryRunner.query(`CREATE TABLE "temporary_sessions" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "status" varchar(50) NOT NULL DEFAULT ('created'), "phone" varchar(20), "pushName" varchar(100), "config" text NOT NULL DEFAULT ('{}'), "proxyUrl" varchar(255), "proxyType" varchar(10), "connectedAt" text, "lastActiveAt" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_ac984ccbd8b01af155e1874e8cb" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "temporary_sessions"("id", "name", "status", "phone", "pushName", "config", "proxyUrl", "proxyType", "connectedAt", "lastActiveAt", "createdAt", "updatedAt") SELECT "id", "name", "status", "phone", "pushName", "config", "proxyUrl", "proxyType", "connectedAt", "lastActiveAt", "createdAt", "updatedAt" FROM "sessions"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`ALTER TABLE "temporary_sessions" RENAME TO "sessions"`);
        await queryRunner.query(`CREATE TABLE "temporary_webhooks" ("id" varchar PRIMARY KEY NOT NULL, "sessionId" varchar NOT NULL, "url" varchar(2048) NOT NULL, "events" text NOT NULL DEFAULT ('["message.received"]'), "secret" varchar(255), "headers" text NOT NULL DEFAULT ('{}'), "active" boolean NOT NULL DEFAULT (1), "retryCount" integer NOT NULL DEFAULT (3), "lastTriggeredAt" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_d209715bb62b12255e825580af6" FOREIGN KEY ("sessionId") REFERENCES "sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_webhooks"("id", "sessionId", "url", "events", "secret", "headers", "active", "retryCount", "lastTriggeredAt", "createdAt", "updatedAt") SELECT "id", "sessionId", "url", "events", "secret", "headers", "active", "retryCount", "lastTriggeredAt", "createdAt", "updatedAt" FROM "webhooks"`);
        await queryRunner.query(`DROP TABLE "webhooks"`);
        await queryRunner.query(`ALTER TABLE "temporary_webhooks" RENAME TO "webhooks"`);
        await queryRunner.query(`CREATE TABLE "temporary_message_batches" ("id" varchar PRIMARY KEY NOT NULL, "batch_id" varchar NOT NULL, "session_id" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "messages" text NOT NULL, "options" text, "progress" text, "results" text, "current_index" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "started_at" text, "completed_at" text, CONSTRAINT "UQ_ff274470c0dbaff6c7d1f9795f5" UNIQUE ("batch_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_message_batches"("id", "batch_id", "session_id", "status", "messages", "options", "progress", "results", "current_index", "created_at", "updated_at", "started_at", "completed_at") SELECT "id", "batch_id", "session_id", "status", "messages", "options", "progress", "results", "current_index", "created_at", "updated_at", "started_at", "completed_at" FROM "message_batches"`);
        await queryRunner.query(`DROP TABLE "message_batches"`);
        await queryRunner.query(`ALTER TABLE "temporary_message_batches" RENAME TO "message_batches"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "message_batches" RENAME TO "temporary_message_batches"`);
        await queryRunner.query(`CREATE TABLE "message_batches" ("id" varchar PRIMARY KEY NOT NULL, "batch_id" varchar NOT NULL, "session_id" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "messages" text NOT NULL, "options" text, "progress" text, "results" text, "current_index" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "started_at" datetime, "completed_at" datetime, CONSTRAINT "UQ_ff274470c0dbaff6c7d1f9795f5" UNIQUE ("batch_id"))`);
        await queryRunner.query(`INSERT INTO "message_batches"("id", "batch_id", "session_id", "status", "messages", "options", "progress", "results", "current_index", "created_at", "updated_at", "started_at", "completed_at") SELECT "id", "batch_id", "session_id", "status", "messages", "options", "progress", "results", "current_index", "created_at", "updated_at", "started_at", "completed_at" FROM "temporary_message_batches"`);
        await queryRunner.query(`DROP TABLE "temporary_message_batches"`);
        await queryRunner.query(`ALTER TABLE "webhooks" RENAME TO "temporary_webhooks"`);
        await queryRunner.query(`CREATE TABLE "webhooks" ("id" varchar PRIMARY KEY NOT NULL, "sessionId" varchar NOT NULL, "url" varchar(2048) NOT NULL, "events" text NOT NULL DEFAULT ('["message.received"]'), "secret" varchar(255), "headers" text NOT NULL DEFAULT ('{}'), "active" boolean NOT NULL DEFAULT (1), "retryCount" integer NOT NULL DEFAULT (3), "lastTriggeredAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_d209715bb62b12255e825580af6" FOREIGN KEY ("sessionId") REFERENCES "sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "webhooks"("id", "sessionId", "url", "events", "secret", "headers", "active", "retryCount", "lastTriggeredAt", "createdAt", "updatedAt") SELECT "id", "sessionId", "url", "events", "secret", "headers", "active", "retryCount", "lastTriggeredAt", "createdAt", "updatedAt" FROM "temporary_webhooks"`);
        await queryRunner.query(`DROP TABLE "temporary_webhooks"`);
        await queryRunner.query(`ALTER TABLE "sessions" RENAME TO "temporary_sessions"`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "status" varchar(50) NOT NULL DEFAULT ('created'), "phone" varchar(20), "pushName" varchar(100), "config" text NOT NULL DEFAULT ('{}'), "proxyUrl" varchar(255), "proxyType" varchar(10), "connectedAt" datetime, "lastActiveAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_ac984ccbd8b01af155e1874e8cb" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "sessions"("id", "name", "status", "phone", "pushName", "config", "proxyUrl", "proxyType", "connectedAt", "lastActiveAt", "createdAt", "updatedAt") SELECT "id", "name", "status", "phone", "pushName", "config", "proxyUrl", "proxyType", "connectedAt", "lastActiveAt", "createdAt", "updatedAt" FROM "temporary_sessions"`);
        await queryRunner.query(`DROP TABLE "temporary_sessions"`);
        await queryRunner.query(`DROP INDEX "IDX_f0680ed02caf690b052be1d6cb"`);
        await queryRunner.query(`DROP TABLE "user_onboarding"`);
        await queryRunner.query(`ALTER TABLE "webhooks" RENAME TO "temporary_webhooks"`);
        await queryRunner.query(`CREATE TABLE "webhooks" ("id" varchar PRIMARY KEY NOT NULL, "sessionId" varchar NOT NULL, "url" varchar(2048) NOT NULL, "events" text NOT NULL DEFAULT ('["message.received"]'), "secret" varchar(255), "headers" text NOT NULL DEFAULT ('{}'), "active" boolean NOT NULL DEFAULT (1), "retryCount" integer NOT NULL DEFAULT (3), "lastTriggeredAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_d209715bb62b12255e825580af6" FOREIGN KEY ("sessionId") REFERENCES "sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "webhooks"("id", "sessionId", "url", "events", "secret", "headers", "active", "retryCount", "lastTriggeredAt", "createdAt", "updatedAt") SELECT "id", "sessionId", "url", "events", "secret", "headers", "active", "retryCount", "lastTriggeredAt", "createdAt", "updatedAt" FROM "temporary_webhooks"`);
        await queryRunner.query(`DROP TABLE "temporary_webhooks"`);
    }

}
